### PR TITLE
Hallo

### PR DESCRIPTION
**Pull request by jnvandermeer**
I made an AMAZING new feature.

Without any bugs

This is a definite improvement to your code

Best
johan

### CODE REVIEW

**Comment by jnvandermeer** [comment]
Comment!

**Comment by AlistairPerry** [comment]
go away

**Comment by AlistairPerry** [comment]
pls clean your office

**Comment by jnvandermeer** [comment]
I'm surprised Matt didn't accept my feature yet.

Didn't I say it was amazing and a definite improvement? I sense some editorial prejudice here.

**Pull request merged**
